title: ak_site
description: "ak_site"
baseurl: ""
url: ""
tagline: "||||||||||||||||||||||"
category: ""
collections_dir: projects
collections:
  appreciate:
    output: true
    permalink: /:collection/:appreciate/:name
  matter:
    output: true
    permalink: /:collection/:matter/:name

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
kramdown:
    auto_ids: false
paginator: enable 
paginate: 200
paginate_path: '/blog/page:num/'
permalink: /blog/:categories/:year/:title/

